language: c

compiler:
  - gcc

jobs:
  include:
  - name: 'Run linux kernel checkpatch.pl script'
    script: make -C driver check
  - name: 'Build kernel module with linux-4.4.0 headers'
    arch: amd64
    dist: xenial
    before_install:
    - sudo apt-get -y install libelf-dev
    - sudo apt-get -y install linux-headers-4.4.0-184-generic
    script:
    - KERNEL_VERSION=4.4.0-184-generic KERNEL_HAS_PARPORT=1 make -C driver
  - name: 'Build kernel module with linux-4.4.0 headers'
    arch: arm64
    dist: xenial
    before_install:
    - sudo apt-get -y install libelf-dev
    - sudo apt-get -y install linux-headers-4.4.0-184-generic
    script:
    - KERNEL_VERSION=4.4.0-184-generic KERNEL_HAS_PARPORT=1 make -C driver
  - name: 'Build kernel module with linux-4.15.0 headers'
    arch: amd64
    dist: bionic
    before_install:
    - sudo apt-get -y install libelf-dev
    - sudo apt-get -y install linux-headers-4.15.0-106-generic
    script:
    - KERNEL_VERSION=4.15.0-106-generic KERNEL_HAS_PARPORT=1 make -C driver
  - name: 'Build kernel module with linux-4.15.0 headers'
    arch: arm64
    dist: bionic
    before_install:
    - sudo apt-get -y install libelf-dev
    - sudo apt-get -y install linux-headers-4.15.0-106-generic
    script:
    - KERNEL_VERSION=4.15.0-106-generic KERNEL_HAS_PARPORT=1 make -C driver
